### ISSUE TITLE
Not All Countries Have States

### ISSUE THREAD

**Issue by erayaydin** [ichtrojan/laravel-location#15]
Hello,

In Turkey, we have not states. We only have cities and towns. Because of this, there are duplicated items on cities and states. For example; `Istanbul` in `CitiesTableSeeder` and also `Istanbul` in `StatesTableSeeder`

**Comment by ichtrojan** [comment]
Can you please correct it in a PR

**Comment by reachfirst7054** [comment]
There is an issue with country Pakistan as well.

**Comment by djunehor** [comment]
One way to fix this is to add `country_id` column to `cities` table. Then create a relationship between City and Country Models. One can then create a route to get cities by country e.g `Route::get('country/{countryId}/cities', 'LocationController@getCitiesByCountry');`
