### ISSUE TITLE
Big Seeder File

### ISSUE THREAD

**Issue by erayaydin** [ichtrojan/laravel-location#16]
Hello,

Its a feature issue; maybe loading country/city/state data from a json file is better way for seeding. Because currently, editing single file is little bit **hard**. Maybe we can create 1 nested json `data.json` or 3 json file `countries.json`,`cities.json` and `states.json` files.

Its easy for development this package with more contributor.

> PS: This json files can also generated by package developers and contributors.

**Comment by ichtrojan** [comment]
I'd be happy to see a pull request from you 😀

**Comment by ichtrojan** [comment]
Scratch that, reading data that large from JSON files will be a bit slower that just reading from a DB.

**Comment by erayaydin** [comment]
It's not "reading from a DB", its read from JSON file and seed to DB @ichtrojan . For example;

```php
// CitiesTableSeeder
// Todo: Use File facade for interact with file
DB::table($citiesTable)->insert(json_decode(file_get_contents('cities.json'))));
```
