### ISSUE TITLE
Table name should be extendible

### ISSUE THREAD

**Issue by erayaydin** [ichtrojan/laravel-location#17]
Hello,

Currently, table names _hardcoded_ . Maybe with a _config_ variable, we can set **extendible** for table names. We'll use that _config_ variable on **migration**,**model** and **seeder** files. 

For example;

```
return [
  ...
  'tables' => [
    'countries' => 'my_countries',
    'cities' => 'my_cities',
    'states' => 'my_states',
  ]
  ...
];
```

**Comment by ichtrojan** [comment]
Great idea, I'd be happy to see a PR.

**Comment by ichtrojan** [comment]
#21
