### ISSUE TITLE
Laravel 8: Table Seeder 

### ISSUE THREAD

**Issue by sahamilton** [ichtrojan/laravel-location#36]
Using a clean install of Laravel 8 when running composer dump-autoload
`Deprecation Notice: Class Ichtrojan\Location\Seeds\StatesTableSeeder located in C:/laragon/www/mapminer4/vendor/ichtrojan/laravel-location/src\database\seeds\StatesTableSeeder.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/laragon/bin/composer/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201`

So when the seeders are run the following error is received:
`Target class [Ichtrojan\\Location\\Seeds\\LocationDatabaseSeeder] does not exist.`

**Comment by gaborm74** [comment]
As a workaround add the below to your composer.json

```json
    "autoload": {
<...>
        "psr-4": {
		<...>
		"Ichtrojan\\Location\\Seeds\\": "vendor/ichtrojan/laravel-location/src/database/seeds/"
        }
    },
```

**Comment by solamichealolawale** [comment]
I followed this fix for Laravel8, it fixed the error message but then I can't run the seeder
`php artisan db:seed --class=Ichtrojan\\Location\\Seeds\\LocationDatabaseSeeder`
it displayed this error message
![image](https://user-images.githubusercontent.com/12444227/111272342-c82fe180-8632-11eb-8e9c-7ddf6fc093ce.png)

**Comment by ekpono** [comment]
I am having the same error @ichtrojan 

STEPS TO REPRODUCE
Laravel 8
PHP 7.4
1.  composer require ichtrojan/laravel-location

ERROR:
  Class Ichtrojan\Location\Seeds\LocationDatabaseSeeder does not exist  

<img width="892" alt="Screen Shot 2021-03-20 at 3 31 43 PM" src="https://user-images.githubusercontent.com/35940495/111873643-9ea7ea80-8991-11eb-86ea-a2fa1aae0833.png">

**Comment by ichtrojan** [comment]
Run 

`composer dump-autoload`
